### PR TITLE
Use git/refs api to be specific instead of parsing a possibly large response

### PR DESCRIPTION
**Pull request by richard-bt**
Howdy!

I was running in to an issue with using the /branches API endpoint. It's possible for that endpoint to require pagination and so if the searched for branch wasn't on the first results page it'd report a false negative.

I've rewired things to use the git/refs/heads or git/refs/tags endpoints so that dealing with pagination isn't necessary. This should also cut down on the amount of data to handle in the response from the GitHub API.

### CODE REVIEW

**Comment by richard-bt** [comment]
It seems that I've rate limited my IP address in testing. I'll have to wait until I get home to look at that AssertionError.

**Comment by tunnckoCore** [comment]
hmm can you share url? I mean your current actual use case url?
so `git/refs` will display all? without pagination? hm.

**Comment by tunnckoCore** [comment]
> https://developer.github.com/v3/git/refs/#get-all-references

it always have pages.. we should hanld that

**Comment by richard-bt** [comment]
I'm not able to share the actual use case url, but you should be able to verify false positive with any other repository with many branches and picking a branch further down on the list of branches. e.g. `joyent/node` and branch `v0.10.30-release`.

I'm not using just `git/refs` to get all refs. What this does instead is tries to see if the specific branch/tag exists at the `git/refs/heads/<branchName>` or `git/refs/tags/<tagName>` endpoint. If the request fails with a 404 we know that branch/tag doesn't exist. If it succeeds, we'll get back a JSON object with a `ref` attribute which will have the ref we're looking for within it.

See:
https://developer.github.com/v3/git/refs/#get-a-reference

I think this querying for the existence of the branch/tag directly is more efficient that querying for the entire list of branches/tags and searching that list.

> it always have pages.. we should han[dle] that

I'm not requesting all of the refs from `git/refs`, so it shouldn't be necessary to handle parsing all different refs. 

> also L85-L90 should stay, b/c what about if show more that 1 result?

Querying this way there should only ever be one result.

**Comment by tunnckoCore** [comment]
hm yea, didn't notice that.

**Comment by tunnckoCore** [comment]
@richard-bt would it be problem for you to not merge this PR, but implement it?

**Comment by tunnckoCore** [comment]
cuz in addition I'll do some more refactoring of whole module, actually error handling

**Comment by tunnckoCore** [comment]
but hey, thanks for the issue in anyway! :)

**Comment by tunnckoCore** [comment]
@richard-bt I'm ready, just waiting travis, cuz he is rate limited.

**Comment by tunnckoCore** [comment]
@richard-bt done, published as v2. Thought it's a lot better and clean.
**breaking change:** give `opts.token` instead just `token` as second argument

**Pull request closed without merging**
